import { PrismaClient, TaskCategory } from "@prisma/client";

const prisma = new PrismaClient();

const documentTypes = [
  {
    name: "EPC",
    description: "Energieprestatiecertificaat (verplicht bij verkoop).",
  },
  {
    name: "Asbestattest",
    description: "Asbestinventaris voor woningen gebouwd voor 2001.",
  },
  {
    name: "Elektrische keuring",
    description: "Verslag van de elektrische installatie.",
  },
  {
    name: "Bodemattest (OVAM)",
    description: "Bodemattest voor vastgoedtransacties in Vlaanderen.",
  },
  {
    name: "Stedenbouwkundige inlichtingen",
    description: "Uittreksel met stedenbouwkundige info.",
  },
  {
    name: "Eigendomsakte",
    description: "Laatste notariële aankoopakte.",
  },
  {
    name: "Kadastraal inkomen",
    description: "Officieel kadastraal inkomen.",
  },
  {
    name: "Installatiehandleidingen",
    description: "Handleidingen voor technische installaties (indien van toepassing).",
    required: false,
  },
];

const taskTemplates = [
  // Administratief & juridisch
  {
    category: TaskCategory.ADMIN_LEGAL,
    title: "Kadastraal uittreksel opvragen",
    description: "Vraag het recentste kadastraal uittreksel aan.",
    costMinEuro: 10,
    costMaxEuro: 30,
    durationDays: 7,
    impactWeight: 4,
  },
  {
    category: TaskCategory.ADMIN_LEGAL,
    title: "Eigendomsakte verzamelen",
    description: "Verzamel de notariële aankoopakte.",
    costMinEuro: 0,
    costMaxEuro: 25,
    durationDays: 3,
    impactWeight: 3,
  },
  {
    category: TaskCategory.ADMIN_LEGAL,
    title: "Stedenbouwkundige inlichtingen aanvragen",
    description: "Aanvraag bij gemeente.",
    costMinEuro: 40,
    costMaxEuro: 120,
    durationDays: 30,
    impactWeight: 5,
  },
  {
    category: TaskCategory.ADMIN_LEGAL,
    title: "Bodemattest aanvragen",
    description: "OVAM bodemattest opvragen.",
    costMinEuro: 30,
    costMaxEuro: 70,
    durationDays: 14,
    impactWeight: 4,
  },
  {
    category: TaskCategory.ADMIN_LEGAL,
    title: "Hypothecaire info controleren",
    description: "Controleer openstaande hypotheken of mandaten.",
    costMinEuro: 0,
    costMaxEuro: 50,
    durationDays: 5,
    impactWeight: 3,
  },
  {
    category: TaskCategory.ADMIN_LEGAL,
    title: "Plannen en vergunningen inventariseren",
    description: "Alle vergunningen en plannen verzamelen.",
    costMinEuro: 0,
    costMaxEuro: 40,
    durationDays: 7,
    impactWeight: 3,
  },
  {
    category: TaskCategory.ADMIN_LEGAL,
    title: "Statuut mede-eigendom controleren",
    description: "Bekijk basisakte en reglement (appartement).",
    costMinEuro: 0,
    costMaxEuro: 60,
    durationDays: 10,
    impactWeight: 4,
  },
  {
    category: TaskCategory.ADMIN_LEGAL,
    title: "Erfdienstbaarheden checken",
    description: "Overzicht van mogelijke erfdienstbaarheden.",
    costMinEuro: 0,
    costMaxEuro: 40,
    durationDays: 5,
    impactWeight: 3,
  },
  {
    category: TaskCategory.ADMIN_LEGAL,
    title: "Verkoopmandaat opmaken (geen makelaar)",
    description: "Intern verkoopmandaat zonder commissie.",
    costMinEuro: 0,
    costMaxEuro: 0,
    durationDays: 1,
    impactWeight: 2,
  },
  {
    category: TaskCategory.ADMIN_LEGAL,
    title: "Compromis-voorbereiding checklist",
    description: "Documenten klaarzetten voor compromis.",
    costMinEuro: 0,
    costMaxEuro: 0,
    durationDays: 2,
    impactWeight: 4,
  },

  // Technisch & veiligheid
  {
    category: TaskCategory.TECH_SAFETY,
    title: "EPC laten opmaken",
    description: "Schakel erkend energiedeskundige in.",
    costMinEuro: 200,
    costMaxEuro: 350,
    durationDays: 10,
    impactWeight: 5,
  },
  {
    category: TaskCategory.TECH_SAFETY,
    title: "Asbestinventaris laten uitvoeren",
    description: "Verplicht voor woningen gebouwd voor 2001.",
    costMinEuro: 250,
    costMaxEuro: 450,
    durationDays: 14,
    impactWeight: 5,
  },
  {
    category: TaskCategory.TECH_SAFETY,
    title: "Elektrische keuring plannen",
    description: "Keuring van elektrische installatie.",
    costMinEuro: 150,
    costMaxEuro: 220,
    durationDays: 7,
    impactWeight: 4,
  },
  {
    category: TaskCategory.TECH_SAFETY,
    title: "Stookolietank attest controleren",
    description: "Attest voor bovengrondse/ondergrondse tank.",
    costMinEuro: 100,
    costMaxEuro: 200,
    durationDays: 10,
    impactWeight: 3,
  },
  {
    category: TaskCategory.TECH_SAFETY,
    title: "Renovatieplicht evalueren",
    description: "Impact van EPC E/F op renovatieplicht.",
    costMinEuro: 0,
    costMaxEuro: 0,
    durationDays: 2,
    impactWeight: 4,
  },
  {
    category: TaskCategory.TECH_SAFETY,
    title: "Keuring liftinstallatie (indien van toepassing)",
    description: "Voor appartementen met lift.",
    costMinEuro: 120,
    costMaxEuro: 200,
    durationDays: 14,
    impactWeight: 2,
  },
  {
    category: TaskCategory.TECH_SAFETY,
    title: "Keuring septic/riolering",
    description: "Controle op aansluiting en keuring.",
    costMinEuro: 80,
    costMaxEuro: 150,
    durationDays: 7,
    impactWeight: 3,
  },
  {
    category: TaskCategory.TECH_SAFETY,
    title: "Ventilatie en vocht inspectie",
    description: "Vochtproblemen uitsluiten.",
    costMinEuro: 0,
    costMaxEuro: 150,
    durationDays: 5,
    impactWeight: 3,
  },
  {
    category: TaskCategory.TECH_SAFETY,
    title: "Installatiehandleidingen verzamelen",
    description: "CV, zonnepanelen, domotica.",
    costMinEuro: 0,
    costMaxEuro: 0,
    durationDays: 2,
    impactWeight: 2,
  },
  {
    category: TaskCategory.TECH_SAFETY,
    title: "Brandveiligheidscheck (rookmelders)",
    description: "Controleer aanwezigheid rookmelders.",
    costMinEuro: 50,
    costMaxEuro: 120,
    durationDays: 3,
    impactWeight: 3,
  },

  // Cosmetisch & presentatie
  {
    category: TaskCategory.COSMETIC_PRESENTATION,
    title: "Ontrommelen en opruimen",
    description: "Minimaliseer persoonlijke spullen.",
    costMinEuro: 0,
    costMaxEuro: 200,
    durationDays: 3,
    impactWeight: 3,
  },
  {
    category: TaskCategory.COSMETIC_PRESENTATION,
    title: "Schilderwerken bijwerken",
    description: "Accentmuren en beschadigingen herstellen.",
    costMinEuro: 150,
    costMaxEuro: 600,
    durationDays: 7,
    impactWeight: 4,
  },
  {
    category: TaskCategory.COSMETIC_PRESENTATION,
    title: "Kleine herstellingen uitvoeren",
    description: "Klinken, kranen, schakelaars.",
    costMinEuro: 50,
    costMaxEuro: 300,
    durationDays: 4,
    impactWeight: 3,
  },
  {
    category: TaskCategory.COSMETIC_PRESENTATION,
    title: "Professionele schoonmaak plannen",
    description: "Dieptereiniging voor fotoshoot.",
    costMinEuro: 120,
    costMaxEuro: 250,
    durationDays: 2,
    impactWeight: 3,
  },
  {
    category: TaskCategory.COSMETIC_PRESENTATION,
    title: "Tuin en buitenruimte opfrissen",
    description: "Snoeien, gazon, terras reinigen.",
    costMinEuro: 80,
    costMaxEuro: 400,
    durationDays: 5,
    impactWeight: 3,
  },
  {
    category: TaskCategory.COSMETIC_PRESENTATION,
    title: "Stylingplan opstellen",
    description: "Kleur- en meubelplan voor presentatie.",
    costMinEuro: 0,
    costMaxEuro: 200,
    durationDays: 2,
    impactWeight: 3,
  },
  {
    category: TaskCategory.COSMETIC_PRESENTATION,
    title: "Verlichting optimaliseren",
    description: "Vervang lampen en versterk licht.",
    costMinEuro: 50,
    costMaxEuro: 150,
    durationDays: 2,
    impactWeight: 2,
  },
  {
    category: TaskCategory.COSMETIC_PRESENTATION,
    title: "Raamdecoratie nalopen",
    description: "Gordijnen reinigen of vervangen.",
    costMinEuro: 0,
    costMaxEuro: 250,
    durationDays: 5,
    impactWeight: 2,
  },
  {
    category: TaskCategory.COSMETIC_PRESENTATION,
    title: "Geurtips en ventilatieplan",
    description: "Neutraliseer geuren tijdens bezoeken.",
    costMinEuro: 20,
    costMaxEuro: 80,
    durationDays: 1,
    impactWeight: 2,
  },
  {
    category: TaskCategory.COSMETIC_PRESENTATION,
    title: "Virtuele homestaging overwegen",
    description: "Digitale staging voor lege ruimtes.",
    costMinEuro: 100,
    costMaxEuro: 250,
    durationDays: 4,
    impactWeight: 2,
  },

  // Marketing & verkoopproces
  {
    category: TaskCategory.MARKETING_SALES,
    title: "Professionele fotoshoot boeken",
    description: "Fotografie en nabewerking.",
    costMinEuro: 200,
    costMaxEuro: 450,
    durationDays: 5,
    impactWeight: 5,
  },
  {
    category: TaskCategory.MARKETING_SALES,
    title: "3D-tour of video plannen",
    description: "Virtuele rondleiding.",
    costMinEuro: 250,
    costMaxEuro: 600,
    durationDays: 7,
    impactWeight: 4,
  },
  {
    category: TaskCategory.MARKETING_SALES,
    title: "Marketingcopy schrijven",
    description: "USP’s en verhaal van de woning.",
    costMinEuro: 0,
    costMaxEuro: 150,
    durationDays: 2,
    impactWeight: 4,
  },
  {
    category: TaskCategory.MARKETING_SALES,
    title: "Publicatieplanning bepalen",
    description: "Wanneer publiceer je op welke kanalen.",
    costMinEuro: 0,
    costMaxEuro: 0,
    durationDays: 1,
    impactWeight: 3,
  },
  {
    category: TaskCategory.MARKETING_SALES,
    title: "Vraagprijsstrategie bepalen",
    description: "Afstemmen met waardescenario’s.",
    costMinEuro: 0,
    costMaxEuro: 0,
    durationDays: 1,
    impactWeight: 5,
  },
  {
    category: TaskCategory.MARKETING_SALES,
    title: "Bezoekmomenten plannen",
    description: "Data en slots voor bezichtigingen.",
    costMinEuro: 0,
    costMaxEuro: 0,
    durationDays: 1,
    impactWeight: 4,
  },
  {
    category: TaskCategory.MARKETING_SALES,
    title: "Lead intake script opstellen",
    description: "Script voor kandidaat-kopers.",
    costMinEuro: 0,
    costMaxEuro: 50,
    durationDays: 2,
    impactWeight: 3,
  },
  {
    category: TaskCategory.MARKETING_SALES,
    title: "Biedingenkalender definiëren",
    description: "Deadlines en biedingsrondes.",
    costMinEuro: 0,
    costMaxEuro: 0,
    durationDays: 1,
    impactWeight: 4,
  },
  {
    category: TaskCategory.MARKETING_SALES,
    title: "Onderhandelingsstrategie voorbereiden",
    description: "Snel vs markt vs maximaal scenario.",
    costMinEuro: 0,
    costMaxEuro: 0,
    durationDays: 2,
    impactWeight: 5,
  },
  {
    category: TaskCategory.MARKETING_SALES,
    title: "Compromisflow communiceren",
    description: "Volgende stappen na acceptatie.",
    costMinEuro: 0,
    costMaxEuro: 0,
    durationDays: 1,
    impactWeight: 4,
  },
];

async function main() {
  await prisma.documentType.deleteMany();
  await prisma.taskTemplate.deleteMany();

  await prisma.documentType.createMany({
    data: documentTypes,
  });

  await prisma.taskTemplate.createMany({
    data: taskTemplates,
  });
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
